
name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu || exit

            if [ ! -d "online-clone-amazon" ]; then
              git clone https://github.com/Priyanka101193Sharma/online-clone-amazon.git
            fi

            cd online-clone-amazon || exit

            minikube status || minikube start --driver=docker

            git reset --hard
            git clean -fd
            git pull origin main

            eval $(minikube docker-env)

            docker build -t amazon-app .

            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
            kubectl apply -f ingress.yml

            kubectl rollout restart deployment amazon-deployment
