name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/online-clone-amazon

            git config pull.rebase false
            git pull origin main

            docker build -t priyankakr/amazon-app:latest .
            docker push priyankakr/amazon-app:latest

            kubectl apply -f deployment.yml
            kubectl apply -f service.yml

            kubectl rollout restart deployment amazon-deployment
